<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>AFMediaBar</AssemblyName>
    <AssemblyTitle>AF Media Bar</AssemblyTitle>
    <RootNamespace>AFMediaBar</RootNamespace>
    <Version>1.1.1</Version>
    <Authors>AmorFate</Authors>
    <Copyright>Copyright (c) 2026 AmorFate</Copyright>
    <RepositoryUrl>https://github.com/Fervent-Tempo/AF-Media-Bar</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Product>AF Media Bar</Product>
    <Description>Media control and minor beautification software for Windows 10/11 desktops.</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(RuntimeIdentifier)' == 'win-x64'">
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AFMediaBar.Core\AFMediaBar.Core.csproj" />
    <ProjectReference Include="..\AFMediaBar.Components.Wpf\AFMediaBar.Components.Wpf.csproj" />
    <ProjectReference Include="..\AFMediaBar.Layout\AFMediaBar.Layout.csproj" />
    <ProjectReference Include="..\AFMediaBar.LayoutEditor.Wpf\AFMediaBar.LayoutEditor.Wpf.csproj" />
    <ProjectReference Include="..\AFMediaBar.Platform.Windows\AFMediaBar.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="unchihugo.WPF-UI" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Players\" />
  </ItemGroup>
</Project>
